version: "3.9"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
      args:
        - RABBITMQ_USER=${RABBITMQ_USER:-user}
        - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-password}
    environment:
      - RABBITMQ_PID_FILE=${RABBITMQ_PID_FILE:-/var/lib/rabbitmq/mnesia/rabbitmq}
    ports:
      - 15672:15672